/* eslint-disable */
// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require('bs-platform/lib/js/block.js');
var Curry = require('bs-platform/lib/js/curry.js');
var Caml_exceptions = require('bs-platform/lib/js/caml_exceptions.js');

var MissingValue = Caml_exceptions.create(
  'Option-GraphiqlExplorer.MissingValue',
);

function $$default(defaultValue, opt) {
  if (opt) {
    return opt[0];
  } else {
    return defaultValue;
  }
}

function expect(name, opt) {
  if (opt) {
    return opt[0];
  } else {
    throw [MissingValue, 'Missing value for ' + name];
  }
}

function map(opt, update) {
  if (opt) {
    return /* Some */ Block.simpleVariant('Some', [Curry._1(update, opt[0])]);
  } else {
    return /* None */ 0;
  }
}

function fmap(opt, update) {
  if (opt) {
    return Curry._1(update, opt[0]);
  } else {
    return /* None */ 0;
  }
}

exports.MissingValue = MissingValue;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
exports.expect = expect;
exports.map = map;
exports.fmap = fmap;
/* No side effect */
